### ISSUE TITLE
What is going on?

### ISSUE THREAD

**Issue by TomasHubelbauer** [fafhrd91/actix-web-postmortem#1]
Hi, I just noticed you wiped this repo and read the entire readme. I've been a passive watcher of Actix ("Watch Releases") so I'm completely out of the loop. I hate reading how you were treated as a maintainer and I fully respect your decision to shelve the project if that's what you're going to do. I am not sure what *the issue* refers to or what went down, but I'd like to plea for the project to be archived if you're on planning on maintaining it anymore, not deleted. You've obviously poured a lot of time and work into it and it would be a real shame for it to be gone, even from your personal repos (not sure what intention you have with those). Archived repos have locked down issues, but the source code remains available for people to fork, read and learn from. Hope you will consider this and wish you the best of luck in and outside of open source maintainership.

**Comment by luojia65** [comment]
Maybe allow us the community join to develop the (opensouce version of) actix better? Or have the Rust team meddle in? This project is an important component of the Rust ecosystem, and many of my (open or closed source) projects depends on it.

---

For all maintainers around actix: please retain and do not remove your crates. Here for new projects decision may depends, but older projects that functions well for millions of users still need your little named work. It's not easy to do the transition overnight. Thanks!

**Comment by shirshak55** [comment]
people didn't treated him properly :(

https://www.reddit.com/r/rust/comments/epszt7/actixnet_unsoundness_patch_is_boring/

Just like other he made benchmark fast and he was called benchmark cheater.
When he didn't accept the code people called him bad maintainer.
Recently someone told him not to write rust code .


After all he also has some life. He has dedicated his time making this project great and the way people treated him is ridiculous.

**Comment by berkus** [comment]
This is not a reason to DELETE a framework many people depend upon.

**Comment by shirshak55** [comment]
I hope so. This is important project I hope it will be restored.

**Comment by jdd-rb** [comment]
I think the Actix-Web project is amazing! I just started using Rust and it's a really well coded, amazing project. I have the biggest gratitude to fafhrd91 and all other contributors for the amazing work they did on this project.

I don't have any demands to restore the project; instead I want to take a moment to express nothing but gratitude. Something that everyone, everywhere should have expressed more a long time ago.

**Comment by luojia65** [comment]
@jddcode Yes that's also why I get loved with Rust. Especially the moment I used actix for the first time and understand how great a Rust project can be.

**Comment by rumatoest** [comment]
@fafhrd91 I understand you. Not so long ago I've found out that there are many active rust community members Who like to learn you how you shold do things.

**Comment by lasiltan** [comment]
Ok... So that was unprofessional. If you don't want to maintain a project anymore, you give it to someone else and link to that repo in your README.

This just screwed me over big time.

**Comment by fafhrd91** [comment]
https://github.com/fafhrd91/actix-net
https://github.com/fafhrd91/actix-web

**Comment by CGOSU** [comment]
我是如此伤心，无论如何都非常希望作者能坚持下去

**Comment by alexyuriev** [comment]
@lasiltan 402. Pay him.

**Comment by cwhy** [comment]
> Ok... So that was unprofessional. If you don't want to maintain a project anymore, you give it to someone else and link to that repo in your README.
> 
> This just screwed me over big time.

He is by not means in a profession to please you.

**Comment by esantoro** [comment]
> Ok... So that was unprofessional. If you don't want to maintain a project anymore, you give it to someone else and link to that repo in your README.
> 
> This just screwed me over big time.

dude, i think you're entitled to a refund of the sum of money that you paid for this code (which is probably zero)

**Comment by SRGOM** [comment]
I sided with the crowd in https://github.com/fafhrd91/actix-web/pull/968#issuecomment-512146519  last time saying that @fafhrd91 should give a look  to the pull since its the OSS contract,  but I will say this- seeing how toxic the Rust community from reddit is (and only from reddit, otherwise it's probably the nicest guys all around) I wish @fafhrd91  a very good luck and  peace of mind. Please do not worry about the crowd.

**Comment by felipecsl** [comment]
https://github.com/actix/actix-web/issues/1#issuecomment-575631809 

For reference, this was the original PR https://github.com/fafhrd91/actix-web/pull/968

**Comment by alekseykorzun** [comment]
> Ok... So that was unprofessional. If you don't want to maintain a project anymore, you give it to someone else and link to that repo in your README.
> 
> This just screwed me over big time.

You are a privileged clown. I suggest you take a good hard look at yourself first and revaluate your approach to things.

**Comment by oblitum** [comment]
> This is not a reason to DELETE a framework many people depend upon.

I disagree. There's no better way for everyone to learn from this bad community experience. For me, this is the best move for community eventually "growing up", or simply rot.

**Comment by nekochan777** [comment]
wow ! this is great !  i 1000% approve this decision.  humans in general is peace of crap and don't worthy so much effort he put in this.

**Comment by oblitum** [comment]
> but I will say this- seeing how toxic the Rust community from reddit is (and only from reddit, otherwise it's probably the nicest guys all around)

There were key Rust people in that sub that took part into this. So I don't view as solely the sub to blame. That actually may sound like shifting blame.

**Comment by BasixKOR** [comment]
This will hopefully remind us that there is people behind every single open source projects.

**Comment by devinus** [comment]
@fafhrd91 I just started building an actix-web project a few days ago and it was a real pleasure. Thank you for all the work you put into it.
