### ISSUE TITLE
We love actix, thank you for creating it!

### ISSUE THREAD

**Issue by octave99** [fafhrd91/actix-web-postmortem#10]
One of the key motivation for me to move my work to Rust was actix-web, and @fafhrd91 has always been kind to offer help at gitter. Actix certainly achieved a lot not just in terms of benchmarks or community around it but also encouraged Rust usage (at least in my case). Infact, actix code also helped enhancing my Rust knowledge while I dig inside, especially the unsafe code (OOPS!!!), and I picked upon some rust unsafe coding practices from actix to enhance performance of my projects, it should be funny to many, and that's fine.

Its pity to see how boundaries were crossed by some folks to discourage a very talented author. I certainly understand that intention was to help actix get secure and better, but it was gradually overtaken by personal egos which should have been avoided. It was not just an attempt to abuse individual's self-esteem but also a community at large which is in love with actix and carried high regards towards its author.

I totally empathize with the author and he has all the rights to move, delete or burn the code into ashes. Future of my 6 actix-web based projects is unknown, but what he has done is absolutely right to let the Rust community introspect upon their behavior, learn from it and become better humans before trying to proclaim as better or safe programmers.

The good part is that situation allowed many users like me to openly express our gratitude towards the project and its author. I also take this opportunity to wish him best of luck for his future endeavours.

The sad part is, it allowed the hate of very few, who might not have even used actix in a single project, win over the love of many active users, using actix across multiple projects, like myself. But that's how hate works, and that's fine.

To restart or permanently close the project is totally @fafhrd91's personal choice, but I sincerely hope that he is now also able to accept the love and gratitude from many real actix users, like also expressed in other issues and comments!

Gentlemen, express some love!

**Comment by ghost** [comment]
I'm just here to agree with the above (_Bump_) •ᴗ• Also, I would like to suggest the idea of archiving the repo like a lot of others have done with their unmaintained projects instead of removing it from public entirely (although if you feel like killing it, go for it; It is your work after all, and your choice what happens with it) - yet, there are a lot of people out there that rely on your hard work daily for theirs and just want to go on with what they're used to. That's it for me. Long live actix!
