### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by dns2utf8** [fafhrd91/actix-web-postmortem#2]
Hi @fafhrd91 

I learned a lot from and with actix!

Wish you all the best

**Comment by fafhrd91** [comment]
thanks!

please, dont open such issues again.

**Comment by Keirua** [comment]
Same for me. Thanks for your great work. Wish you the best.

**Comment by TerminalWitchcraft** [comment]
Just for clarification(my opinion), for all those who reacted with :confused:  emoji on the author's comment, I think the author meant to politely say that there is no need to open `thank you` issues. Issues, as the name says, it for project issues/ideas/features/etc. and not a ideal place to thank author(s) for their work. There are other more suitable means to thank the author(s). 

Kindly do not misinterpret his comment.
