### ISSUE TITLE
Focus on the people that matter

### ISSUE THREAD

**Issue by sharonjl** [fafhrd91/actix-web-postmortem#24]
I am just passing by since I am only working with rust as a hobby, I thought I'd share my view on all of this maybe it will help you make a decision.

Despite whatever drama, there are still plenty of people that rely on **your** work for their projects, products, and services. These are the people that matter. They are the ones who understand what is important and what isn't.

I am sure you will experience situations in your life that will flay your soul, this probably does as well. But the **choice** is yours, you can let it flay your soul or focus on making a positive impact in the rust community as you have clearly done.

Would you rather your work be remembered as something that was shut down because of internet drama, or remembered as the project that beat the trolls? I know it hurts, but it can't hurt anymore.

**Comment by shirshak55** [comment]
hmm I think actix web / net etc are already restored right? And nothing is broken till now .

**Comment by sharonjl** [comment]
Oh ok, I'm just a dummy :D

**Comment by stappersg** [comment]
> Oh ok, I'm just a dummy :D

And somebody who can close this issue.


(Please close issues that have servered their purpose.)
