### ISSUE TITLE
Why is this being deleted? 

### ISSUE THREAD

**Issue by Snipey** [fafhrd91/actix-web-postmortem#8]
I just don't understand why you would  go back and take back everything you have done.

**Comment by komawoyo** [comment]
Author's choice, he don't need to provide a reason

**Comment by netroy** [comment]
Perhaps the author should provide a reason by listing all the toxic people & their toxic behaviours. so the rest of the community can learn more about how & when to protect open-source maintainers.

There is no place for entitled bullies in FOSS.

**Comment by qmdx** [comment]
Please put those unfriendly voice as fart, look forward to your return
